# Generated by ChatGPT on 2025-10-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add extended rating fields
        migrations.AddField(
            model_name="review",
            name="rating_service",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_value",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_quality",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_cleanliness",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="review",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),

        # New model for attachments
        migrations.CreateModel(
            name="ReviewAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("file", models.FileField(upload_to="review_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reviews.review",
                    ),
                ),
            ],
        ),

        # New model for helpful votes
        migrations.CreateModel(
            name="ReviewVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("is_helpful", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="reviews.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("review", "user")},
                "indexes": [models.Index(fields=["review", "user"], name="reviews_revi_review_60d999_idx")],
            },
        ),

        # New model for reports/flags
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam or irrelevant"),
                            ("offensive", "Offensive or abusive"),
                            ("fake", "Fake or misleading"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="reviews.review",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("review", "reporter")},
                "indexes": [models.Index(fields=["review", "reporter"], name="reviews_revi_review_4d1cf9_idx")],
            },
        ),
    ]