# Generated by Django 5.2.6 on 2025-10-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_extended_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reviewreport',
            new_name='reviews_rev_review__fb4058_idx',
            old_name='reviews_revi_review_4d1cf9_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewvote',
            new_name='reviews_rev_review__94634e_idx',
            old_name='reviews_revi_review_60d999_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
