# Generated by Django 5.2.6 on 2025-10-23 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(help_text='e.g., 1, 137, 56', max_length=20)),
                ('contract_address', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('erc20', 'ERC-20'), ('erc721', 'ERC-721')], default='erc20', max_length=10)),
                ('min_balance_wei', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('required_token_id', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='start_date',
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='generate_codes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_claims',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='promotion',
            name='total_claimed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='promotion',
            name='token_gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='promotions.tokengate'),
        ),
        migrations.CreateModel(
            name='PromoClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=64)),
                ('signed_message', models.TextField(blank=True, default='')),
                ('signature', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='promotions.promotion')),
            ],
            options={
                'unique_together': {('promotion', 'wallet_address')},
            },
        ),
    ]
