# Generated by Django 5.2.6 on 2025-10-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnChainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SIGNED_REVIEW', 'Signed Review'), ('TX_LINKED', 'Tx Linked')], db_index=True, max_length=20)),
                ('wallet_address', models.CharField(help_text='Ethereum or other blockchain wallet address (e.g. 0xabc...).', max_length=42)),
                ('network', models.CharField(blank=True, help_text='Blockchain network, e.g. Ethereum, Polygon, etc.', max_length=50)),
                ('proof', models.TextField(blank=True, help_text='Optional proof or transaction data verifying this record.')),
                ('chain', models.CharField(blank=True, max_length=16, null=True)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.business')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
