# Generated by Django 5.2.6 on 2025-10-06 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('onchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onchainrecord',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onchain_records', to='directory.business'),
        ),
    ]
