# Generated by Django 5.2.6 on 2025-10-06 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=42)),
                ('chain', models.CharField(db_index=True, default='eth', max_length=32)),
                ('scheme', models.CharField(db_index=True, default='eip191', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('address',), name='uniq_wallet_address_globally'), models.UniqueConstraint(fields=('user', 'address'), name='uniq_user_address_pair')],
            },
        ),
    ]
