# Generated by Django 5.2.6 on 2025-10-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
