# Generated by Django 5.2.6 on 2025-10-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Numeric score for this business, e.g. 0.0 – 5.0')),
                ('comment', models.TextField(blank=True, help_text='Optional commentary on the score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='directory.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
